baseURL = 'https://pablo.town/'
languageCode = 'en-us'
title = 'pablo.town'
disablePathToLower = true

[taxonomies]
  tag = 'tags'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = 'catppuccin-mocha'
